updated design for passwords and login/signup pages
hpi-swt2/compass-portal-blue pull request #157
Opened 2022-01-14 15:56 UTC by taminob

does-not-really-close #155 (but half of it)

![image](https://user-images.githubusercontent.com/28907748/149545355-04a266e1-3f6b-4949-9bfa-9a41be683c60.png)
![image](https://user-images.githubusercontent.com/28907748/149545391-eeace859-7dae-40b4-994b-8fdcfc03d8f8.png)

2022-01-21 14:31 UTC, cambryx requested changes
Looks good!

You should rebase the newest version of dev into this branch, then we can merge

2022-01-21 19:17 UTC, taminob commented
@Tratori if you approve, we can merge this

2022-01-24 10:20 UTC, cambryx approved these changes
Looks good

2022-01-24 12:12 UTC, Tratori approved these changes

2022-01-24 12:12 UTC, merged