Improve design for internal pages 2
hpi-swt2/compass-portal-blue pull request #161
Opened 2022-01-18 14:16 UTC by taminob

closes #155 (second part)

2022-01-21 09:24 UTC, bewee commented on app/views/rooms/index.html.erb
> +      <% Room.room_type_to_external_mapping.each do |internal,external| %>
Nice!

2022-01-21 13:02 UTC, BenediktV commented
There will be conflicts with other branches.
There are conflicts regarding the styling of the show pages with #131.
Also there is at least one issue with #127 because the back and edit buttons on the show pages should not get displayed anymore.

2022-01-21 15:00 UTC, cambryx requested changes
Looks really good!
We are a big fan of the rooms index page refactoring.

For some lines in tests we don't understand why they were removed.

Dev should be rebased into this branch before we can merge

2022-01-21 19:18 UTC, bewee commented on spec/views/rooms/show.html.erb_spec.rb
> -    expect(rendered).to match(/Room Type/)
ups

2022-01-21 19:22 UTC, bewee commented on spec/views/rooms/edit.html.erb_spec.rb
> -      assert_select "input[name=?]", "room[room_type]"
definitely

2022-01-24 10:33 UTC, cambryx approved these changes
Looks good

2022-01-24 12:14 UTC, Tratori approved these changes

2022-01-24 12:20 UTC, merged