Feature/hg 77 creating rooms hpi campus i
hpi-swt2/compass-portal-blue pull request #163
Opened 2022-01-20 11:24 UTC by hpistudent72

Added Indoor Maps for ABC-Gebäude and Hauptgebäude. Additionally updated the map for Hörsaalgebäude.

2022-01-20 15:20 UTC, oleschl commented
I don't know how you exported the geojson however your rooms use a LineString instead of a Polygon for the room geometry.

2022-01-20 16:36 UTC, oleschl commented
The lines of the rooms of the main building are crooked and look a little messy sometimes. That could be improved but would take some time. @ClFeSc  and @anonym-HPI  what is your opinion on this?
Current:
![Screenshot from 2022-01-20 16-08-05](https://user-images.githubusercontent.com/49571011/150380034-45bd4a96-e6ee-41a7-968d-7bb351b3103f.png)

Quick improve attempt:
![Screenshot from 2022-01-20 16-18-51](https://user-images.githubusercontent.com/49571011/150380037-501ba7bc-0651-434d-b9cd-fe3abbcb448e.png)

2022-01-21 11:11 UTC, hpistudent72 commented
> I don't know how you exported the geojson however your rooms use a LineString instead of a Polygon for the room geometry.

I created them just using save as. Oddly enough I can't open the geojsons using polygons in JOSM. Did you use another extension that wasn't mentioned? Either way editing the geojsons to swap LineString for Polygon shouldn't take long, but I can't  use them afterwards if there are points we have to move.

2022-01-23 21:35 UTC, ClFeSc requested changes
I tried importing the geojson files in order to see them, but it fails for me for all buildings but the ABC building with some logs like `feature has no valid level name and will be skipped:  gorund` and `Uncaught (in promise) Error: Invalid LatLng object: (NaN, NaN)`. Please add a working method of import to the branch so that the content can actually be used.

2022-01-23 21:37 UTC, ClFeSc commented
> The lines of the rooms of the main building are crooked and look a little messy sometimes. That could be improved but would take some time. @ClFeSc and @anonym-HPI what is your opinion on this? Current: ![Screenshot from 2022-01-20 16-08-05](https://user-images.githubusercontent.com/49571011/150380034-45bd4a96-e6ee-41a7-968d-7bb351b3103f.png)
> 
> Quick improve attempt: ![Screenshot from 2022-01-20 16-18-51](https://user-images.githubusercontent.com/49571011/150380037-501ba7bc-0651-434d-b9cd-fe3abbcb448e.png)

I don't really like the offset, but I don't think it's worth the hassle and the time improving it. Unless @anonym-HPI says it should be done.

2022-01-25 13:35 UTC, Dassderdie commented on app/assets/geojsons/HG_-1.geojson
> +                ]
1. to see see the rooms one has to add 
```js
  await loadGeoJsonFile("/assets/H_0.geojson");
  await loadGeoJsonFile("/assets/H_1.geojson");
  await loadGeoJsonFile("/assets/H_2.geojson");
  await loadGeoJsonFile("/assets/H_3.geojson");
  await loadGeoJsonFile("/assets/HG_-1.geojson");
  await loadGeoJsonFile("/assets/HS_0.geojson");
```
into `leafletMap.js`.
(or the more performant way)

```js
    await Promise.all(
        loadGeoJsonFile('/assets/ABC-Building-0.geojson'),
        loadGeoJsonFile('/assets/ABC-Building-1.geojson'),
        loadGeoJsonFile('/assets/H_0.geojson'),
        loadGeoJsonFile('/assets/H_1.geojson'),
        loadGeoJsonFile('/assets/H_2.geojson'),
        loadGeoJsonFile('/assets/H_3.geojson'),
        loadGeoJsonFile('/assets/HG_-1.geojson'),
        loadGeoJsonFile('/assets/HS_0.geojson')
    );
```.

Then the js errors with:
```log
leaflet-src.js:1280 Uncaught (in promise) Error: Invalid LatLng object: (undefined, undefined)
    at new LatLng (leaflet-src.js:1280:1)
    at coordsToLatLng (leaflet-src.js:8320:1)
    at coordsToLatLngs (leaflet-src.js:8331:1)
    at coordsToLatLngs (leaflet-src.js:8331:1)
    at geometryToLayer (leaflet-src.js:8289:1)
    at NewClass.addData (leaflet-src.js:8200:1)
    at NewClass.addData (leaflet-src.js:8187:1)
    at NewClass.initialize (leaflet-src.js:8170:1)
    at new NewClass (leaflet-src.js:296:1)
    at Object.geoJSON (leaflet-src.js:8502:1)
```

It seems to me like this is caused by incorrect Polygon coordiantes.
In the (working ABC geojsons there is another array around the coordinates in the polygon):
```suggestion
                "coordinates": [[
                    [
                        13.13219416721,
                        52.39397398336
                    ],
                    [
                        13.13208460674,
                        52.39396990756
                    ],
                    [
                        13.13207924232,
                        52.39402146549
                    ],
                    [
                        13.13218842279,
                        52.39402490812
                    ],
                    [
                        13.13219039206,
                        52.39401088823
                    ],
                    [
                        13.13219416721,
                        52.39397398336
                    ]
                ]]
```

2022-01-25 13:39 UTC, Dassderdie commented on app/assets/geojsons/HG_-1.geojson
> +                ]
In TS:

```ts
// currently:
type Coordinates = [number, number][]
// correct:
type Coordinates = [[number, number][]]

```

2022-01-25 19:23 UTC, ClFeSc requested changes
I don't know whether the calculation of the label/marker positions is correct here?
![Bildschirmfoto vom 2022-01-25 20-17-59](https://user-images.githubusercontent.com/68013019/151044836-511ffa0d-1111-4e0e-abda-3e7a277b7d9a.png)

Other than that, just some minor points.

2022-01-25 19:23 UTC, ClFeSc commented on app/javascript/packs/leafletMap.js
> +        feature.geometry.type == "Polygon"? feature.geometry.coordinates : feature.geometry.coordinates[0],
```suggestion
        feature.geometry.type === "Polygon" ? feature.geometry.coordinates : feature.geometry.coordinates[0],
```

2022-01-25 19:23 UTC, ClFeSc commented on app/javascript/packs/leafletMap.js
> +    await loadGeoJsonFile("/assets/H_2.geojson");
```suggestion
    await loadGeoJsonFile("/assets/H_2.geojson");
    await loadGeoJsonFile("/assets/H_3.geojson");
```

2022-01-25 19:23 UTC, ClFeSc commented on app/javascript/packs/leafletMap.js
> +        layerControl.addBaseLayer(newLayer, feature.properties.level_name);
Could we somehow manage to order these layers? The order currently is `0` -> `1` -> `2` -> `-1`.

2022-01-25 20:07 UTC, Dassderdie commented on app/javascript/packs/leafletMap.js
> +    await loadGeoJsonFile("/assets/HG_-1.geojson");
Use `Promise.all()` to parallelize the loading of the geojsons.

2022-01-25 22:05 UTC, ClFeSc reviewed
I'm now happy with it, but as I changed some things, I like another one (@Dassderdie maybe) to take another look to approve.

2022-01-25 22:08 UTC, ClFeSc commented
I don't know why the test fails, the tested behaviour works for me as far as I can tell.

2022-01-25 23:32 UTC, anonym-HPI commented
> The lines of the rooms of the main building are crooked and look a little messy sometimes. That could be improved but would take some time. @ClFeSc and @anonym-HPI what is your opinion on this? Current: ![Screenshot from 2022-01-20 16-08-05](https://user-images.githubusercontent.com/49571011/150380034-45bd4a96-e6ee-41a7-968d-7bb351b3103f.png)
> 
> Quick improve attempt: ![Screenshot from 2022-01-20 16-18-51](https://user-images.githubusercontent.com/49571011/150380037-501ba7bc-0651-434d-b9cd-fe3abbcb448e.png)

Sorry, just saw it now. If you mean the entrance (at the door), that is not important, but the pink lines behind of the building make it look not good. A way, would be to hide them in indoor mode, if putting them exactly on top, is a problem. But they should not be too far off, to be noticed when zooming in and out (and then the building "jumps" a bit in a direction or deforms).

2022-01-26 10:09 UTC, Dassderdie approved these changes
LGTM

2022-01-26 16:19 UTC, ClFeSc commented
What should we do about the CodeFactor? It only mentions files not modified in this PR.

2022-01-29 18:39 UTC, ClFeSc commented
> What should we do about the CodeFactor? It only mentions files not modified in this PR.

I have just clicked on 'Fix that' in the CodeFactor menu.

2022-01-29 18:42 UTC, ClFeSc approved these changes
Should be fine (I hope so).

2022-02-01 12:14 UTC, JulianEgbert commented
Please notify our team (T.O.B.I.A.S) via Discord when this is merged.
We can then extend our indoor routing to these buildings.

2022-02-02 09:36 UTC, anonym-HPI approved these changes
visual review approved (descriptions will be hidden in name tag in a seperate issue)

2022-02-02 09:37 UTC, merged