Feature/cmjd 126 calendar
hpi-swt2/compass-portal-blue pull request #191
Opened 2022-01-26 08:25 UTC by speydril

close #126 

This PR needs #125 

We used the simple_calendar gem for the visualization. We also added a model for events which are also stored in the database.
For now you can view calendars for each room, which query the database in that moment

2022-02-02 10:51 UTC, Storyxx requested changes
Nice code, but there are still a few issues, feel free to implement better code than I suggested 😀

2022-02-02 10:51 UTC, Storyxx commented on app/views/events/_form.html.erb
> +  </div>
There is a big time zone problem here, which can be fixed (at least if the server is run in the same time zone as the users) by inserting:
```ruby
Time.zone = Time.now.zone
```
Somewhere prominent in the code.
It is even possible to add it into the `config/application.rb` like this:
```ruby
config.time_zone = Time.now.zone
```

2022-02-02 10:51 UTC, Storyxx commented on app/views/rooms/calendar.html.erb
> +<%= week_calendar(number_of_weeks: 1, events: @events) do |date, events| %>
This currently **crashes** when, logging in, adding an event for today with a room set and opening the calendar for that room!

2022-02-02 10:51 UTC, Storyxx commented on spec/helpers/events_helper_spec.rb
> +# end
maybe remove

2022-02-03 13:00 UTC, Storyxx approved these changes
Look great 😄

2022-02-08 16:41 UTC, JessicaDierking commented
![image](https://user-images.githubusercontent.com/68076323/153033426-328f6e7f-22f9-40c0-989a-c9b3b8c1deee.png)
There seems to be a problem with showing the names of the weekdays when the language is switched to german.

2022-02-09 13:13 UTC, johannes-poetzsch commented
> Looks really neat, good job!
> 
> The only thing that I noticed is that success messages are shown twice: as an alert and again as notice below. Happens for creating, updating as well as destroying events. Could you remove the non-alert-notices?
> 
> ![image](https://user-images.githubusercontent.com/49537067/152845590-06899b7c-78de-4044-86ae-4904012c9dcd.png)

The additional notices have been removed

2022-02-10 12:41 UTC, JessicaDierking approved these changes

2022-02-10 21:11 UTC, merged

2022-02-10 21:39 UTC, niklasmohrin commented on true
> +      create    db/migrate/20220120141537_change_column.rb
:thinking: