Feature/rh 180_email_and_tel_clickable
hpi-swt2/compass-portal-blue pull request #204
Opened 2022-01-28 13:51 UTC by rfrx

* closes #180 
* now users can click on people's phone numbers resp. email addresses on people show and index page and can directly call resp. email the person

2022-01-28 14:56 UTC, TheGrayStone requested changes
Looks good 👍 

I've just some little change requests.

(Also: It seems you still have to deal with code factor)

2022-01-28 14:56 UTC, TheGrayStone commented on app/javascript/packs/ajax.js
> +      }
Maybe shrinking it down a bit would be better:

```suggestion
      if (href.startsWith("mailto:") || href.startsWith("tel:")){
        return;
      }
```

Or even something like:
```suggestion
      if (href.match(/(mailto|tel):(.*)/)) {
        return;
      }
```

2022-01-28 14:56 UTC, TheGrayStone commented on app/javascript/packs/ajax.js
> +   if (target === "/route") {
I suspect this is a space too much 😅 
```suggestion
  if (target === "/route") {
```

2022-01-28 14:56 UTC, TheGrayStone commented on app/views/people/index.html.erb
> +        <td><%= tel_to person.phone_number %></td>
I like the helpers 👍

2022-02-04 09:11 UTC, philbow61 reviewed
Good Job 👍

2022-02-04 09:17 UTC, TheGrayStone approved these changes

2022-02-04 09:31 UTC, merged