Add import script and add (german) names to buildings.geojson
hpi-swt2/compass-portal-blue pull request #248
Opened 2022-02-11 10:28 UTC by TheGrayStone

Closes #225 

You can use `bundle exec rails db:seed` to execute the script.

2022-02-14 12:49 UTC, oleschl commented on app/assets/geojsons/buildings.geojson
> -                    [13.125011, 52.3948757],
I think you mixed up the buildings. Buildings B is [13.12..., 52.39]

2022-02-14 12:50 UTC, oleschl commented on app/assets/geojsons/buildings.geojson
> -                    [13.125011, 52.3948757],
A and C are also off

2022-02-15 10:49 UTC, oleschl commented
- Büro -> office
- Arbeitsraum -> office
- ELT-Raum (elektrischer Betriebsraum) -> electrical-room
- Teeküche -> tea-kitchen
- Kopierraum -> copy-room
- Abstellraum -> storage
- Technikraum -> mechanical-room
- Schalterraum -> counter-room
- BMZ (Brandmeldezentrale) -> fire-alarm-system
- Putzraum -> cleaning-room
- komische Räume -> other

2022-02-16 08:33 UTC, ClFeSc requested changes
I haven't looked in detail through the changes in the geojsons. I noticed two things:
1. When doing navigation with rooms, outdoor ways are not displayed (although indoor lines are). Also, Pin-to-Pin navigation (outdoor) works as expected.
2. The rooms to be a bit off. E.g. room A-2.3 is not where it should be: ![Bild](https://user-images.githubusercontent.com/68013019/154225727-f7373ec5-1ad3-4425-933d-fc618b03a90d.png)
Note that the indoor navigation has correct locations.

2022-02-16 08:58 UTC, oleschl commented
> I haven't looked in detail through the changes in the geojsons. I noticed two things:
> 
>     1. When doing navigation with rooms, outdoor ways are not displayed (although indoor lines are). Also, Pin-to-Pin navigation (outdoor) works as expected.
> 
>     2. The rooms to be a bit off. E.g. room A-2.3 is not where it should be: ![Bild](https://user-images.githubusercontent.com/68013019/154225727-f7373ec5-1ad3-4425-933d-fc618b03a90d.png)
>        Note that the indoor navigation has correct locations.

The room is not off but a click will only move the map to the center of its building. We could open a new issue and change this.
On my machine outdoor lines are displayed. Are you sure that you selected level 0?

2022-02-16 09:22 UTC, ClFeSc commented
> On my machine outdoor lines are displayed. Are you sure that you selected level 0?

Ah, I see. I thought these lines would be dotted as the indoor lines on other floors are.

2022-02-16 09:51 UTC, ClFeSc commented
> The room is not off but a click will only move the map to the center of its building. We could open a new issue and change this.

I've created #268 for this.

2022-02-16 09:52 UTC, ClFeSc approved these changes
As the problem with the centering is now another issue, I think this is good to go (although I didn't check every room and room number).

2022-02-16 10:27 UTC, oleschl commented
How to test:

- run rails db:seed
- test the search function on the main page eg search for A-E
- visit http://localhost:3000/rooms

2022-02-16 12:00 UTC, hpistudent72 approved these changes

2022-02-17 12:50 UTC, merged