Feature/13 list search results
hpi-swt2/compass-portal-blue pull request #26
Opened 2021-11-25 17:58 UTC by maximilian-franz

Closes #13

2021-11-28 16:56 UTC, Storyxx commented
@chrisma Why exactly is `codeclimate` broken? Clicking on details doesn't seem to lead to any problems with our code, so what is the issue here?

2021-11-28 17:02 UTC, chrisma commented
Hi @Storyxx, CodeFactor seems to work fine on this branch as far as I can tell.

2021-12-02 12:33 UTC, johannes-poetzsch commented on app/controllers/search_results_controller.rb
> +  # GET /search_results or /search_results.json
GET /search_results.json is not an available route so it should not be listed here.

2021-12-02 12:33 UTC, johannes-poetzsch commented on app/controllers/search_results_controller.rb
> +  end
According to the [Ruby Style Guide](https://rubystyle.guide/) empty methods should be written like: `def destroy; end`.

2021-12-03 11:12 UTC, johannes-poetzsch approved these changes

2021-12-03 11:52 UTC, johannes-poetzsch requested changes

2021-12-03 11:52 UTC, johannes-poetzsch commented on app/controllers/search_results_controller.rb
> +    params.fetch(:search_result, {})
Use `require` and `permit` to define which parameters should be accepted. More Information can be found [here](https://guides.rubyonrails.org/v6.0/getting_started.html#saving-data-in-the-controller).

2021-12-04 10:50 UTC, johannes-poetzsch approved these changes

2021-12-06 16:05 UTC, johannes-poetzsch approved these changes

2021-12-06 16:15 UTC, merged