9_ building_data-model and 8_room_data_model
hpi-swt2/compass-portal-blue pull request #29
Opened 2021-11-29 17:56 UTC by Max784

2021-11-30 14:27 UTC, bewee requested changes
Looks good overall. We really like the solution with Timeable! Just some small things & comments

2021-11-30 14:27 UTC, bewee commented on app/models/building.rb
> +end
Looks a bit empty, aren't some fields missing here? 🤔

2021-11-30 14:27 UTC, bewee commented on db/schema.rb
> +  add_foreign_key "rooms", "buildings"
Why is there no foreign key between users and buildings?

2021-11-30 14:27 UTC, bewee commented on spec/factories/openingtimes.rb
> +    closes { "2021-11-29 07:41:48" }
Why does it store the date, not only the time? 
Also, I would prefer the sample being opened for at least one second ;) 
(Also, maybe add validation that closes - opens is > 0)

2021-11-30 14:27 UTC, bewee commented on spec/factories/rooms.rb
> +    contact_person { "Jonas Cremerius" }
Should be reference to (already existing) users relation

2021-11-30 14:27 UTC, bewee commented on spec/helpers/buildings_helper_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
Pending tests, but we could still fill these in a later PR

2021-11-30 14:27 UTC, bewee commented on spec/models/openingtime_spec.rb
> +    expect(openingtime.day).to eq(1)
Should also test the other fields

2021-11-30 14:27 UTC, bewee commented on spec/models/room_spec.rb
> +  it "has a building" do
after making user a foreign key, also add a "has a user" test

2021-11-30 14:27 UTC, bewee commented on app/models/building.rb
> +end
Why is this empty? How does it work with no fields specified? o.O We are confused :D
(same for timeable.rb and rooms.rb)

2021-12-03 10:27 UTC, taminob approved these changes
Validation of attributes in models and especially tests are still open and have to be implemented at a later point.
To have at least some progress, we can merge this

2021-12-03 11:40 UTC, bewee approved these changes

2021-12-03 11:41 UTC, bewee commented on spec/factories/openingtimes.rb
> +    closes { "2021-11-29 07:41:48" }
Update: Only validation still missing

2021-12-03 11:41 UTC, merged