Merge Feature/rh 47
hpi-swt2/compass-portal-blue pull request #94
Opened 2021-12-10 16:55 UTC by BenediktV

Openingtimes can be added in the edit person page.
The day can be selected as a string in a dropdown instead of the number

2021-12-13 16:04 UTC, rfrx requested changes

2021-12-13 16:04 UTC, rfrx commented on spec/models/openingtime_spec.rb
> +  before(:each) do
```suggestion
  before :each do
```

2021-12-13 16:04 UTC, rfrx commented on spec/models/openingtime_spec.rb
> +  before(:each) do
I'm not sure, whether that's the linter's desire, but in my opinion the linter should be pleased before merging

2021-12-14 10:06 UTC, rfrx approved these changes

2021-12-14 15:04 UTC, TheGrayStone approved these changes
Marvelous!

2021-12-15 08:43 UTC, merged